### ISSUE TITLE
Bot seems to fail if there is a game that is already over and does not accept inputs anymore.

### ISSUE THREAD

**Issue by mpeuster** [fpoppinga/kicktipp-bot#2]
Any ideas?

**Comment by fpoppinga** [comment]
Mhm, I had that one already, and quickly removed it in the last commit, in order to get stuff running - it'll be a dirty worldcup... 

Quick workaround is obviously to make guesses early :-P I'll see what I can do.

**Comment by fpoppinga** [comment]
Ah, fun fact, the bot errors out, but there is actually no problem. Just chill and let it run. Pro tip: If you run it with `yarn start --env window` you can even see what's going on.
